on:
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    steps:
      - run: |
          git clone https://github.com/ultimate-yuri/Q3TA_cooptest.git .
          git checkout ${{github.sha}}
          cd code/game
          set PATH
          ./game_ta.bat
