on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/ultimate-yuri/Q3TA_cooptest.git .
          git checkout ${{github.sha}}
          cd code/game
          pwd
          chmod +x ./game_ta.sh
          ./game_ta.sh
